version: '3.8'

services:
  frontend:
    image: node:18-alpine
    container_name: bank-frontend-dev
    working_dir: /app
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - "4200:4200"
    command: >
      sh -c "npm install && npm start"
    environment:
      - NODE_ENV=development
      - API_URL=http://localhost:8082/api

volumes:
  node_modules:
